name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: wow-profile-copy-ng-linux-git
        path: target/release/wow-profile-copy-ng

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: wow-profile-copy-ng-windows-git
        path: target/release/wow-profile-copy-ng.exe
    
  merge:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: build
          pattern: wow-profile-copy-ng-*
          delete-merged: true

  release:
    runs-on: ubuntu-latest
    needs: merge
    permissions:
      contents: write
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Attach Binaries
        run: gh release upload ${{ github.ref_name }} ./build/*
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
